### ISSUE TITLE
DirectoryListing

### ISSUE THREAD

**Issue by viceice** [FubarDevelopment/WebDavServer#21]
Hi, is it possible to get a directory listing when i do a http get on a directory?

It looks like the ```GetHeadHandler``` explicitly forbids this on get.

Regards
Michael

**Comment by fubar-coder** [comment]
Yes, this is correct. Returning the contents of a collection via HTTP GET isn't supported, because it's not specified what should be returned. You have two options:

1. You can register your own `IGetHandler` on the `IServiceCollection`. When registered after a `AddWebDav`, your handler should overwrite the original handler.
2. Create a new interface (e.g. `IGetCollectionHandler`) which is optional (i.e. has a default value of `null`) for the `GetHeadHandler` and is used to return the content for a GET on a collection.

When you choose option 2, then I'll gladly accept the pull request 😁 .

**Comment by ViceIce** [comment]
OK, I will look at option 2. :grin:

**Comment by petersgiles** [comment]
Is there an example of how to write this in any of the documentation?

I can see [GetHeadHandler](https://fubardevelopment.github.io/WebDavServer/api/FubarDev.WebDavServer.Handlers.Impl.GetHeadHandler.html) in the docs but I have no idea how to add/use it with the GET verb in the controller.

Am I adding a service to the `services.Configure<DotNetFileSystemOptions>`? how should that look?

I've been looking through the sample project and can't see anything that looks like a directory listing.

**Comment by fubar-coder** [comment]
Fixed in the release/2.0 branch.

The library doesn't provide its own implementation, but a sample implementation is available in the sample WebDAV server.
