### ISSUE TITLE
Allow to use json instead of xml for request and response body

### ISSUE THREAD

**Issue by viceice** [FubarDevelopment/WebDavServer#26]
I think a good improvement would be to allow send a `Content-Type: application/json; charset="utf-8"` and `Accept: application/json; charset="utf-8"` header. An process request and response as json.

So the webdav server can be used by javascript more easy.

**Comment by fubar-coder** [comment]
I don't think that it's that easy, because this would've been 100% proprietary. However, you **can** provide your own implementation of `IWebDavOutputFormatter` for the serialization and a custom input formatter (see `WebDavXmlSerializerMvcOptionsSetup`, and `WebDavXmlSerializerInputFormatter`) for the deserialization.

**BUT** be aware that different XML responses with different root node names may be returned for the same request, depending on the amount of response values, and error condition.

I'm hesitant to support this feature, because it would require writing/maintaining a spec and a sample implementation (RFC, anyone?).

**Comment by ViceIce** [comment]
Ok, i will look at the serializers and formatter. Maybe that could be enough to override for our usecase.

**Comment by fubar-coder** [comment]
Closing, JSON payload is not specified by any RFC and it wouldn't be easy to cover all XML features
